"""Autogenerated documentation for `ingest/parsers/__init__.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable
from pathlib import Path

from ..models import ParsedDocument
from .docx import parse_docx
from .html import parse_html
from .image import parse_image
from .pdf import parse_pdf
from .text import parse_text
from .xlsx import parse_xlsx

Parser = Callable[[Path], ParsedDocument]

PARSERS: dict[str, Parser] = {
    ".txt": parse_text,
    ".md": parse_text,
    ".pdf": parse_pdf,
    ".docx": parse_docx,
    ".xlsx": parse_xlsx,
    ".html": parse_html,
    ".htm": parse_html,
    ".png": parse_image,
    ".jpg": parse_image,
    ".jpeg": parse_image,
    ".tif": parse_image,
    ".tiff": parse_image,
}


def discover_documents(content_root: Path) -> Iterable[Path]:
    for path in sorted(content_root.rglob("*")):
        if path.is_file() and path.suffix.lower() in PARSERS:
            yield path


def parse_document(path: Path) -> ParsedDocument:
    parser = PARSERS.get(path.suffix.lower())
    if parser is None:
        raise ValueError(f"Unsupported file extension: {path.suffix}")
    return parser(path)
