"""Autogenerated documentation for `ingest/parsers/text.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from __future__ import annotations

from pathlib import Path

from ..models import ParsedDocument, ParsedSection


def parse_text(path: Path) -> ParsedDocument:
    text = path.read_text(encoding="utf-8")
    section = ParsedSection(text=text, breadcrumbs=["Text"])
    return ParsedDocument(
        source_path=path,
        source_type="text",
        sections=[section],
    )
