config:
  MD013:
    line_length: 400
    heading_line_length: 0
    tables: false
    strict: false
    inner_sentence: true
    code_blocks: false
  MD022: true
  MD024:
    siblings_only: true
    allow_different_nesting: true
  MD025: true
  MD029:
    style: one_or_ordered
  MD032: true
  MD033:
    allowed_elements: ["img","p","br","a","code","em","strong","details","summary"]
  MD036: true
  MD040: true
  MD041: true
  MD012: true
globs:
  - "README.md"
  - "docs/**/*.md"
ignores:
  - "node_modules/**"
  - ".venv/**"
  - "archive/**"
  - "content/**"
  - "eval/**"
  - "reports/**"
