repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - types-requests
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: npx --yes markdownlint-cli2
        language: node
        pass_filenames: true
        types: [markdown]
        additional_dependencies:
          - markdownlint-cli2@0.12.0
