repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
        args: [check, ., --fix]
        exclude: '^_tmp_.*\.py$'
      - id: ruff-format
        exclude: '^_tmp_.*\.py$'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - pydantic-settings
          - types-requests
          - types-PyYAML
        args: ["--config-file=pyproject.toml"]
  - repo: local
    hooks:
      - id: markdownlint-cli2
        name: markdownlint-cli2
        entry: npx --yes markdownlint-cli2
        language: node
        pass_filenames: false
        types: [markdown]
        additional_dependencies:
          - markdownlint-cli2@0.12.0
        args: ["**/*.md", "#node_modules", "#.venv"]
