# Default configuration for the Atticus RAG service.
# Values can be overridden via environment variables (see .env.example).
content_dir: content
indices_dir: indices
logs_path: logs/app.jsonl
errors_path: logs/errors.jsonl
manifest_path: indices/manifest.json
metadata_path: indices/index_metadata.json
snapshots_dir: indices/snapshots
dictionary_path: indices/dictionary.json
database_url: postgresql://postgres:postgres@localhost:5433/atticus
pgvector_lists: 100
pgvector_probes: 4
chunk_size: 512
chunk_overlap_ratio: 0.0
chunk_target_tokens: 512
chunk_min_tokens: 256
chunk_overlap_tokens_setting: 0
max_context_chunks: 10
top_k: 20
embed_model: text-embedding-3-large
embedding_model_version: text-embedding-3-large@2025-01-15
generation_model: gpt-4.1
generation_prompt_version: atticus-v1
confidence_threshold: 0.7
log_level: INFO
timezone: UTC
enforce_gateway_boundary: true
allow_loopback_requests: true
require_forwarded_for_header: true
require_https_forward_proto: true
trusted_gateway_subnets:
  - 127.0.0.1/32
  - ::1/128
evaluation_runs_dir: eval/runs
baseline_path: eval/baseline.json
gold_set_path: eval/gold_set.csv
eval_regression_threshold: 3.0
eval_min_ndcg: 0.55
eval_min_mrr: 0.5
evaluation_modes:
  - hybrid
  - vector
