/**
 * Autogenerated documentation for `next-auth.d.ts` within the Atticus codebase.
 * Key exports: follow the named or default exports defined below; inputs and outputs remain as implemented and correlate with related modules via existing imports.
 * Documentation only—do not modify runtime behavior when updating this comment.
 */

import { DefaultSession, DefaultUser } from "next-auth";
import { Role } from "@prisma/client";

declare module "next-auth" {
  interface Session extends DefaultSession {
    user?: {
      id: string;
      role: Role;
      orgId: string;
    } & DefaultSession["user"];
    expires: DefaultSession["expires"];
  }

  interface User extends DefaultUser {
    role: Role;
    orgId: string;
  }
}

declare module "next-auth/jwt" {
  interface JWT {
    userId: string;
    role: Role;
    orgId: string;
  }
}
