/**
 * Autogenerated documentation for `app/api/glossary/[id]/route.ts` within the Atticus codebase.
 * Key exports: follow the named or default exports defined below; inputs and outputs remain as implemented and correlate with related modules via existing imports.
 * Documentation only—do not modify runtime behavior when updating this comment.
 */

import { NextResponse } from "next/server";
import { GlossaryStatus, Prisma } from "@prisma/client";
import { getServerAuthSession } from "@/lib/auth";
import { withRlsContext } from "@/lib/rls";
import { canEditGlossary } from "@/lib/rbac";
import {
  parseStatus,
  parseSynonyms,
  serializeEntry,
  handleGlossaryError,
  snapshotEntry,
} from "@/app/api/glossary/utils";

const relationSelect = {
  author: { select: { id: true, email: true, name: true } },
  updatedBy: { select: { id: true, email: true, name: true } },
  reviewer: { select: { id: true, email: true, name: true } },
} as const;

export async function PUT(request: Request, { params }: { params: { id: string } }) {
  try {
    const session = canEditGlossary(await getServerAuthSession());
    const payload = await request.json();
    const definition = typeof payload.definition === "string" ? payload.definition.trim() : "";
    if (!definition) {
      return NextResponse.json(
        { error: "invalid_request", detail: "Definition is required." },
        { status: 400 }
      );
    }
    const term = typeof payload.term === "string" && payload.term.trim().length > 0 ? payload.term.trim() : undefined;
    const synonyms = parseSynonyms(payload.synonyms);
    const status = parseStatus(payload.status);
    const reviewNotes =
      typeof payload.reviewNotes === "string"
        ? payload.reviewNotes.trim() || null
        : payload.reviewNotes === null
        ? null
        : undefined;

    const entry = await withRlsContext(session, async (tx) => {
      const existing = await tx.glossaryEntry.findUnique({
        where: { id: params.id },
        include: relationSelect,
      });
      if (!existing) {
        return null;
      }

      const before = snapshotEntry(existing);
      const data: Record<string, unknown> = {
        definition,
        synonyms,
        status,
        updatedById: session.user.id,
      };
      if (term) {
        data.term = term;
      }
      if (reviewNotes !== undefined) {
        data.reviewNotes = reviewNotes;
      }
      if (status === GlossaryStatus.PENDING) {
        data.reviewedAt = null;
        data.reviewerId = null;
      } else {
        data.reviewedAt = new Date();
        data.reviewerId = session.user.id;
      }

      const updated = await tx.glossaryEntry.update({
        where: { id: params.id },
        data,
        include: relationSelect,
      } as any);

      await tx.ragEvent.create({
        data: {
          orgId: session.user.orgId,
          actorId: session.user.id,
          actorRole: session.user.role,
          action: "glossary.updated",
          entity: "glossary",
          glossaryId: updated.id,
          before,
          after: snapshotEntry(updated),
        },
      });

      return updated;
    });

    if (!entry) {
      return NextResponse.json({ error: "not_found" }, { status: 404 });
    }

    return NextResponse.json(serializeEntry(entry));
  } catch (error) {
    return handleGlossaryError(error);
  }
}

export async function PATCH(request: Request, ctx: { params: { id: string } }) {
  return PUT(request, ctx);
}

export async function DELETE(_: Request, { params }: { params: { id: string } }) {
  try {
    const session = canEditGlossary(await getServerAuthSession());
    const result = await withRlsContext(session, async (tx) => {
      const existing = await tx.glossaryEntry.findUnique({ where: { id: params.id } });
      if (!existing) {
        return null;
      }
      await tx.glossaryEntry.delete({ where: { id: params.id } });
      await tx.ragEvent.create({
        data: {
          orgId: session.user.orgId,
          actorId: session.user.id,
          actorRole: session.user.role,
          action: "glossary.deleted",
          entity: "glossary",
          glossaryId: existing.id,
          before: snapshotEntry(existing),
          after: Prisma.JsonNull,
        },
      });
      return true;
    });
    if (result === null) {
      return NextResponse.json({ error: "not_found" }, { status: 404 });
    }
    return NextResponse.json({ status: "ok" });
  } catch (error) {
    return handleGlossaryError(error);
  }
}
