"""Autogenerated documentation for `tests/test_api_version.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from __future__ import annotations

from pathlib import Path

from api.main import app


def test_api_version_matches_repo_version() -> None:
    version_path = Path(__file__).resolve().parents[1] / "VERSION"
    expected = version_path.read_text(encoding="utf-8").strip()
    assert app.version == expected
