/**
 * Autogenerated documentation for `app/page.tsx` within the Atticus codebase.
 * Key exports: follow the named or default exports defined below; inputs and outputs remain as implemented and correlate with related modules via existing imports.
 * Documentation only—do not modify runtime behavior when updating this comment.
 */

import { ChatWorkspace } from "@/components/chat/chat-workspace";

export default function HomePage() {
  return <ChatWorkspace />;
}
