"use client";

/**
 * Autogenerated documentation for `app/providers.tsx` within the Atticus codebase.
 * Key exports: follow the named or default exports defined below; inputs and outputs remain as implemented and correlate with related modules via existing imports.
 * Documentation only—do not modify runtime behavior when updating this comment.
 */

import { SessionProvider } from "next-auth/react";
import type { ReactNode } from "react";
import type { SessionProviderProps } from "next-auth/react";

interface ProvidersProps {
  children: ReactNode;
  session?: SessionProviderProps["session"];
}

export function Providers({ children, session }: ProvidersProps) {
  return <SessionProvider session={session}>{children}</SessionProvider>;
}
