"""Autogenerated documentation for `atticus/notify/__init__.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from .mailer import EscalationDeliveryError, send_escalation

__all__ = ["EscalationDeliveryError", "send_escalation"]
