"use client";

/**
 * Autogenerated documentation for `components/admin/admin-ops-console.tsx` within the Atticus codebase.
 * Key exports: follow the named or default exports defined below; inputs and outputs remain as implemented and correlate with related modules via existing imports.
 * Documentation only—do not modify runtime behavior when updating this comment.
 */

import { useEffect, useMemo, useState, useTransition } from "react";
import { Role } from "@prisma/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { GlossaryAdminPanel, GlossaryEntryDto } from "@/components/glossary/admin-panel";
import { Drawer, DrawerBody, DrawerContent, DrawerFooter, DrawerHeader } from "@/components/ui/drawer";
import { Textarea } from "@/components/ui/textarea";

export type SourceSummary = {
  path: string;
  score: number | null;
  page: number | null;
  heading: string | null;
  chunkId: string | null;
};

export type UncertainChat = {
  id: string;
  question: string;
  answer: string | null;
  confidence: number;
  status: string;
  requestId: string | null;
  createdAt: string;
  topSources: SourceSummary[];
  author: { id: string; email: string | null; name: string | null } | null;
  reviewer: { id: string; email: string | null; name: string | null } | null;
  tickets: Array<{
    id: string;
    key: string;
    status: string;
    assignee: string | null;
    lastActivity: string | null;
  }>;
  followUpPrompt: string | null;
  auditLog: Array<Record<string, unknown>>;
};

export type TicketSummary = {
  id: string;
  key: string;
  status: string;
  assignee: string | null;
  lastActivity: string | null;
  summary: string | null;
};

interface AdminOpsConsoleProps {
  role: Role;
  uncertain: UncertainChat[];
  tickets: TicketSummary[];
  glossaryEntries: GlossaryEntryDto[];
}

function confidenceVariant(confidence: number): "success" | "warning" | "destructive" {
  if (confidence >= 0.75) {
    return "success";
  }
  if (confidence >= 0.45) {
    return "warning";
  }
  return "destructive";
}

export function AdminOpsConsole({ role, uncertain, tickets, glossaryEntries }: AdminOpsConsoleProps) {
  const [uncertainChats, setUncertainChats] = useState(uncertain);
  const [ticketSummaries, setTicketSummaries] = useState(tickets);
  const [feedback, setFeedback] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();
  const [drawerChatId, setDrawerChatId] = useState<string | null>(null);
  const [followUpDraft, setFollowUpDraft] = useState("");

  const canApprove = role === Role.ADMIN || role === Role.REVIEWER;
  const canEscalate = role === Role.ADMIN;
  const canManageGlossary = role === Role.ADMIN;
  const defaultTab = role === Role.ADMIN ? "uncertain" : "glossary";

  const activeChat = useMemo(
    () => uncertainChats.find((chat) => chat.id === drawerChatId) ?? null,
    [drawerChatId, uncertainChats]
  );

  useEffect(() => {
    setFollowUpDraft(activeChat?.followUpPrompt ?? "");
  }, [activeChat?.followUpPrompt, drawerChatId]);

  function openDrawer(chatId: string) {
    setDrawerChatId(chatId);
    setFeedback(null);
  }

  async function handleApprove(chatId: string) {
    if (!canApprove) {
      return;
    }
    setFeedback(null);
    startTransition(async () => {
      const response = await fetch(`/api/admin/uncertain/${chatId}/approve`, { method: "POST" });
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        setFeedback(body.detail ?? "Unable to approve chat.");
        return;
      }
      setUncertainChats((prev) => prev.filter((chat) => chat.id !== chatId));
      setFeedback("Chat approved and removed from the uncertain queue.");
      if (drawerChatId === chatId) {
        setDrawerChatId(null);
      }
    });
  }

  async function handleEscalate(chat: UncertainChat) {
    if (!canEscalate) {
      return;
    }
    setFeedback(null);
    startTransition(async () => {
      const response = await fetch(`/api/admin/uncertain/${chat.id}/escalate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ summary: chat.question, assignee: chat.tickets.at(0)?.assignee ?? null }),
      });
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        setFeedback(body.detail ?? "Unable to escalate chat.");
        return;
      }
      const ticket = (await response.json()) as TicketSummary;
      setUncertainChats((prev) => prev.filter((item) => item.id !== chat.id));
      setTicketSummaries((prev) => [{ ...ticket, summary: chat.question }, ...prev]);
      setFeedback(`Escalated to ticket ${ticket.key}.`);
      if (drawerChatId === chat.id) {
        setDrawerChatId(null);
      }
    });
  }

  function updateChat(chatId: string, partial: Partial<UncertainChat>) {
    setUncertainChats((prev) => prev.map((chat) => (chat.id === chatId ? { ...chat, ...partial } : chat)));
  }

  async function handleFollowUpSave(chat: UncertainChat) {
    if (!canApprove) {
      return;
    }
    const trimmed = followUpDraft.trim();
    if (!trimmed) {
      setFeedback("Add a follow-up prompt before saving.");
      return;
    }
    setFeedback(null);
    startTransition(async () => {
      const response = await fetch(`/api/admin/uncertain/${chat.id}/ask-followup`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: trimmed }),
      });
      if (!response.ok) {
        const body = await response.json().catch(() => ({}));
        setFeedback(body.detail ?? "Unable to store follow-up prompt.");
        return;
      }
      const payload = await response.json();
      updateChat(chat.id, { followUpPrompt: payload.followUpPrompt, auditLog: payload.auditLog ?? [] });
      setFeedback("Follow-up prompt saved.");
    });
  }

  const ticketCount = ticketSummaries.length;
  const pendingCount = uncertainChats.length;

  const ticketCards = useMemo(
    () =>
      ticketSummaries.map((ticket) => {
        const lastActivity = ticket.lastActivity ? new Date(ticket.lastActivity).toLocaleString() : "N/A";
        return (
          <Card key={ticket.id} className="border-slate-200 dark:border-slate-800">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center justify-between text-base">
                <span>{ticket.key}</span>
                <Badge variant="outline" className="capitalize">
                  {ticket.status}
                </Badge>
              </CardTitle>
              <CardDescription>Assigned to {ticket.assignee ?? "Unassigned"}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-2 text-sm text-slate-600 dark:text-slate-300">
              <p>{ticket.summary ?? "No summary provided."}</p>
              <p className="text-xs text-slate-500 dark:text-slate-400">Last activity: {lastActivity}</p>
            </CardContent>
          </Card>
        );
      }),
    [ticketSummaries]
  );

  return (
    <>
      <Tabs defaultValue={defaultTab} className="space-y-6">
        <TabsList>
          <TabsTrigger aria-label="Uncertain" value="uncertain">Uncertain ({pendingCount})</TabsTrigger>
          <TabsTrigger aria-label="Tickets" value="tickets">Tickets ({ticketCount})</TabsTrigger>
          <TabsTrigger aria-label="Glossary" value="glossary">Glossary</TabsTrigger>
      </TabsList>
      {feedback ? (
        <Badge variant="subtle" className="normal-case">
          {feedback}
        </Badge>
      ) : null}
      <TabsContent value="uncertain">
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Question</TableHead>
                <TableHead>Confidence</TableHead>
                <TableHead>Top sources</TableHead>
                <TableHead>Requester</TableHead>
                <TableHead>Created</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {uncertainChats.map((chat) => (
                <TableRow key={chat.id}>
                  <TableCell className="max-w-xs align-top">
                    <p className="font-medium text-slate-900 dark:text-white">{chat.question}</p>
                    {chat.requestId ? (
                      <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">Request {chat.requestId}</p>
                    ) : null}
                  </TableCell>
                  <TableCell className="align-top">
                    <Badge variant={confidenceVariant(chat.confidence)}>
                      {(chat.confidence * 100).toFixed(0)}%
                    </Badge>
                  </TableCell>
                  <TableCell className="align-top text-sm text-slate-600 dark:text-slate-300">
                    <ul className="space-y-1">
                      {chat.topSources.length ? (
                        chat.topSources.map((source, index) => (
                          <li key={`${chat.id}-source-${index}`} className="flex flex-col">
                            <span className="truncate text-xs text-slate-500 dark:text-slate-400">
                              {source.path}
                            </span>
                            {source.heading ? (
                              <span className="text-xs text-slate-400 dark:text-slate-500">
                                {source.heading}
                              </span>
                            ) : null}
                            <div className="flex flex-wrap gap-2 text-[11px] text-slate-400 dark:text-slate-500">
                              {source.page != null ? <span>Page {source.page}</span> : null}
                              {source.score != null ? (
                                <span>Score {(source.score * 100).toFixed(1)}%</span>
                              ) : null}
                              {source.chunkId ? <span>{source.chunkId}</span> : null}
                            </div>
                          </li>
                        ))
                      ) : (
                        <li className="text-xs text-slate-500 dark:text-slate-400">No sources captured.</li>
                      )}
                    </ul>
                  </TableCell>
                  <TableCell className="align-top text-sm text-slate-600 dark:text-slate-300">
                    <p>{chat.author?.name ?? chat.author?.email ?? "Unknown"}</p>
                  </TableCell>
                  <TableCell className="align-top text-sm text-slate-600 dark:text-slate-300">
                    {new Date(chat.createdAt).toLocaleString()}
                  </TableCell>
                  <TableCell className="align-top text-right">
                    <div className="flex flex-col items-end gap-2">
                      <Button
                        type="button"
                        size="sm"
                        onClick={() => openDrawer(chat.id)}
                        variant="default"
                      >
                        Review
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant="secondary"
                        disabled={!canApprove || isPending}
                        onClick={() => handleApprove(chat.id)}
                      >
                        Approve
                      </Button>
                      <Button
                        type="button"
                        size="sm"
                        variant="outline"
                        disabled={!canEscalate || isPending}
                        onClick={() => handleEscalate(chat)}
                      >
                        Escalate
                      </Button>
                    </div>
                  </TableCell>
                </TableRow>
              ))}
              {uncertainChats.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="py-8 text-center text-sm text-slate-500 dark:text-slate-400">
                    All caught up. Pending review chats will appear here automatically.
                  </TableCell>
                </TableRow>
              ) : null}
            </TableBody>
          </Table>
        </div>
      </TabsContent>
      <TabsContent value="tickets">
        <div className="grid gap-4 md:grid-cols-2">{ticketCards}</div>
        {ticketSummaries.length === 0 ? (
          <Card className="mt-4 border-dashed">
            <CardHeader>
              <CardTitle>No escalations yet</CardTitle>
              <CardDescription>
                Approve chats or escalate them to create AE tickets that appear in this queue.
              </CardDescription>
            </CardHeader>
          </Card>
        ) : null}
      </TabsContent>
      <TabsContent value="glossary" className="p-0">
        <GlossaryAdminPanel initialEntries={glossaryEntries} canEdit={canManageGlossary} />
      </TabsContent>
      </Tabs>
      <Drawer
        open={drawerChatId !== null}
        onOpenChange={(open: boolean) => {
          if (!open) {
            setDrawerChatId(null);
            setFollowUpDraft("");
          }
        }}
      >
        <DrawerContent>
          <DrawerHeader>
            <div className="flex-1">
              <p className="text-xs uppercase text-slate-400">Review uncertain chat</p>
              <p className="mt-1 text-base font-semibold text-slate-900 dark:text-white">
                {activeChat?.question ?? "No chat selected"}
              </p>
              {activeChat ? (
                <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                  Captured {new Date(activeChat.createdAt).toLocaleString()}
                </p>
              ) : null}
            </div>
          </DrawerHeader>
          <DrawerBody>
            {activeChat ? (
              <div className="space-y-6">
                <div className="flex flex-wrap items-center gap-3">
                  <Badge variant={confidenceVariant(activeChat.confidence)}>
                    {(activeChat.confidence * 100).toFixed(1)}%
                  </Badge>
                  {activeChat.requestId ? (
                    <span className="text-xs text-slate-500 dark:text-slate-400">
                      Request {activeChat.requestId}
                    </span>
                  ) : null}
                  <span className="text-xs capitalize text-slate-500 dark:text-slate-400">
                    Status {activeChat.status}
                  </span>
                </div>
                <section className="space-y-2">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Answer</h3>
                  <div className="rounded-md border border-slate-200 bg-slate-50 p-4 text-sm leading-relaxed text-slate-700 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200">
                    {activeChat.answer?.length ? activeChat.answer : "No answer captured for this request."}
                  </div>
                </section>
                <section className="space-y-2">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Top sources</h3>
                  <ul className="space-y-2 text-xs text-slate-500 dark:text-slate-400">
                    {activeChat.topSources.length ? (
                      activeChat.topSources.map((source, index) => (
                        <li key={`${activeChat.id}-drawer-source-${index}`} className="rounded-md border border-slate-200 p-3 dark:border-slate-800">
                          <p className="font-medium text-slate-700 dark:text-slate-200">{source.path}</p>
                          {source.heading ? <p className="mt-1">{source.heading}</p> : null}
                          <div className="mt-2 flex flex-wrap gap-3">
                            {source.page != null ? <span>Page {source.page}</span> : null}
                            {source.score != null ? <span>Score {(source.score * 100).toFixed(1)}%</span> : null}
                            {source.chunkId ? <span>{source.chunkId}</span> : null}
                          </div>
                        </li>
                      ))
                    ) : (
                      <li>No sources recorded for this chat.</li>
                    )}
                  </ul>
                </section>
                <section className="space-y-2">
                  <h3 className="text-sm font-semibold text-slate-900 dark:text-white">Follow-up prompt</h3>
                  <Textarea
                    value={followUpDraft}
                    onChange={(event) => setFollowUpDraft(event.target.value)}
                    minLength={3}
                    rows={4}
                    placeholder="What would you ask next?"
                    disabled={!canApprove || isPending}
                  />
                  {activeChat.followUpPrompt ? (
                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      Last saved prompt: “{activeChat.followUpPrompt}”
                    </p>
                  ) : null}
                </section>
              </div>
            ) : (
              <p className="text-sm text-slate-500 dark:text-slate-400">Select a chat to review details.</p>
            )}
          </DrawerBody>
          <DrawerFooter className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap gap-2">
              <Button
                type="button"
                size="sm"
                disabled={!activeChat || !canApprove || isPending}
                onClick={() => activeChat && handleFollowUpSave(activeChat)}
              >
                Save follow-up
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={!activeChat || !canApprove || isPending}
                onClick={() => activeChat && handleApprove(activeChat.id)}
              >
                Approve
              </Button>
              <Button
                type="button"
                size="sm"
                variant="outline"
                disabled={!activeChat || !canEscalate || isPending}
                onClick={() => activeChat && handleEscalate(activeChat)}
              >
                Escalate
              </Button>
            </div>
            <div className="text-xs text-slate-500 dark:text-slate-400">
              Actions are recorded in the chat audit trail.
            </div>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
    </>
  );
}
