#!/usr/bin/env python3
"""Autogenerated documentation for `scripts/generate_env.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path


def _fingerprint(value: str | None) -> str | None:
    if not value:
        return None
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:12]


DEFAULTS = {
    # Core models
    "OPENAI_API_KEY": "sk-your-openai-key",
    "EMBED_MODEL": "text-embedding-3-large",
    "EMBEDDING_MODEL_VERSION": "text-embedding-3-large@2025-01-15",
    "GEN_MODEL": "gpt-4.1",
    "CONFIDENCE_THRESHOLD": "0.70",
    "CHUNK_TARGET_TOKENS": "512",
    "CHUNK_MIN_TOKENS": "256",
    "CHUNK_OVERLAP_TOKENS": "100",
    "MAX_CONTEXT_CHUNKS": "10",
    "ENABLE_RERANKER": "0",
    "TOP_K": "20",
    "EVAL_REGRESSION_THRESHOLD": "3.0",
    # Paths & storage
    "CONTENT_ROOT": "./content",
    "INDICES_DIR": "./indices",
    "LOG_PATH": "./logs/app.jsonl",
    "ERROR_LOG_PATH": "./logs/errors.jsonl",
    "DICTIONARY_PATH": "./indices/dictionary.json",
    # Database & vector search
    "DATABASE_URL": "postgresql://atticus:atticus@localhost:5432/atticus",
    "POSTGRES_DB": "atticus",
    "POSTGRES_USER": "atticus",
    "POSTGRES_PASSWORD": "atticus",
    "PGVECTOR_LISTS": "100",
    "PGVECTOR_PROBES": "4",
    # Logging & telemetry
    "LOG_LEVEL": "INFO",
    "LOG_VERBOSE": "0",
    "LOG_TRACE": "0",
    "LOG_FORMAT": "json",
    "TIMEZONE": "UTC",
    # Rate limiting
    "RATE_LIMIT_REQUESTS": "5",
    "RATE_LIMIT_WINDOW_SECONDS": "60",
    # Notifications & escalation
    "CONTACT_EMAIL": "atticus-contact@example.com",
    "SMTP_HOST": "smtp.example.com",
    "SMTP_PORT": "587",
    "SMTP_USER": "smtp-user",
    "SMTP_PASS": "change-me-smtp-password",
    "SMTP_FROM": "atticus-escalations@example.com",
    "SMTP_TO": "atticus-technical-support@example.com",
    "SMTP_DRY_RUN": "1",
    "EMAIL_SANDBOX": "true",
    "SMTP_ALLOW_LIST": "",
    # Auth & admin
    "AUTH_SECRET": "dev-secret",
    "NEXTAUTH_SECRET": "dev-secret",
    "NEXTAUTH_URL": "http://localhost:3000",
    "NEXTAUTH_URL_INTERNAL": "http://localhost:3000",
    "DEFAULT_ORG_ID": "org-atticus",
    "DEFAULT_ORG_NAME": "Atticus Default",
    "ADMIN_EMAIL": "admin@atticus.local",
    "ADMIN_NAME": "Atticus Admin",
    "ADMIN_API_TOKEN": "set-a-strong-admin-token",
    "AUTH_DEBUG_MAILBOX_DIR": "./logs/mailbox",
    # Local email sandbox
    "EMAIL_SERVER_HOST": "localhost",
    "EMAIL_SERVER_PORT": "1025",
    "EMAIL_SERVER_USER": "",
    "EMAIL_SERVER_PASSWORD": "",
    "EMAIL_FROM": "no-reply@atticus.local",
    # Frontend/API integration
    "RAG_SERVICE_URL": "http://localhost:8000",
    "ASK_SERVICE_URL": "http://localhost:8000",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a .env file for Atticus")
    parser.add_argument("--force", action="store_true", help="overwrite an existing .env file")
    parser.add_argument(
        "--ignore-env",
        action="store_true",
        help="ignore host environment variables when populating values",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    env_path = root / ".env"

    if env_path.exists() and not args.force:
        print(f"[generate_env] .env already exists at {env_path}. Use --force to overwrite.")
        return 0

    if args.ignore_env:
        print("[generate_env] Ignoring host environment variables; writing defaults.")

    lines = []
    used_openai_key: str | None = None
    for k, v in DEFAULTS.items():
        if args.ignore_env:
            val = v
        else:
            val = os.environ.get(k, v)
        if isinstance(val, str):
            val = val.strip()
        if k == "OPENAI_API_KEY":
            used_openai_key = val
        lines.append(f"{k}={val}")

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[generate_env] Wrote {env_path}")
    if used_openai_key:
        source = (
            "environment" if not args.ignore_env and "OPENAI_API_KEY" in os.environ else "defaults"
        )
        fingerprint = _fingerprint(used_openai_key) or "none"
        print(f"[generate_env] OPENAI_API_KEY resolved from {source} (fingerprint={fingerprint})")
    else:
        print(
            "[generate_env] Note: OPENAI_API_KEY is empty. Set it via environment before running, e.g.\n"
            "  PowerShell:  $env:OPENAI_API_KEY='sk-...' ; python scripts/generate_env.py --force\n"
            "  Bash:        OPENAI_API_KEY='sk-...' python scripts/generate_env.py --force"
        )
    if (
        not args.ignore_env
        and "OPENAI_API_KEY" in os.environ
        and os.environ.get("OPENAI_API_KEY", "").strip() != (used_openai_key or "")
    ):
        print(
            "[generate_env] Warning: host OPENAI_API_KEY differs from written value. Run with --ignore-env to bypass host overrides."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
