#!/usr/bin/env python3
"""Autogenerated documentation for `scripts/run_ingestion.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from __future__ import annotations

import runpy
from pathlib import Path


def main() -> None:
    target = Path(__file__).with_name("ingest_cli.py")
    runpy.run_path(str(target), run_name="__main__")


if __name__ == "__main__":
    main()
