"""Autogenerated documentation for `retriever/__init__.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from .models import Answer, Citation
from .service import answer_question
from .vector_store import VectorStore

__all__ = ["Answer", "Citation", "VectorStore", "answer_question"]
