"""Autogenerated documentation for `api/routes/__init__.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from . import admin, chat, eval, health, ingest, ui

__all__ = ["admin", "chat", "eval", "health", "ingest", "ui"]
