"""Autogenerated documentation for `api/routes/health.py` within the Atticus project.

This module participates in the documentation pipeline by summarizing the purpose and exports declared below without altering runtime semantics.
Key exports: review the functions, classes, and constants defined in this file when tracing dependencies across the codebase.
Documentation only—do not change runtime behavior when updating this note.
"""

from fastapi import APIRouter

from atticus.config import load_manifest

from ..dependencies import SettingsDep
from ..schemas import HealthResponse

router = APIRouter()


@router.get("/health", response_model=HealthResponse)
async def health(settings: SettingsDep) -> HealthResponse:
    manifest = load_manifest(settings.manifest_path)
    return HealthResponse(
        status="ok",
        manifest_present=manifest is not None,
        document_count=manifest.document_count if manifest else 0,
        chunk_count=manifest.chunk_count if manifest else 0,
        embedding_model=(manifest.embedding_model if manifest else settings.embed_model),
        embedding_model_version=(
            manifest.embedding_model_version if manifest else settings.embedding_model_version
        ),
    )
