name: Auto-fix Ruff

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-fix-ruff-${{ github.head_ref }}
  cancel-in-progress: false

jobs:
  ruff-fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip ruff

      - name: Apply ruff fixes
        run: |
          ruff format .
          ruff check . --fix

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply ruff auto-fixes"
          branch: ${{ github.head_ref }}

