name: Evaluation Gate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  evaluation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run evaluation
        run: python scripts/eval_run.py --json --output-dir eval/runs/ci

      - name: Upload evaluation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-ci
          path: eval/runs/ci
