name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install project + dev tools
        run: |
          python -m pip install --upgrade pip
          # Installs your package and dev extras (ruff, mypy, pytest, pydantic, etc.)
          python -m pip install -e ".[dev]"
          python -m pip install pre-commit

      - name: Show tool versions
        run: |
          python --version
          ruff --version
          mypy --version
          pytest --version

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .

      - name: Type check
        run: |
          # Grab stubs for common third-party libs if available (non-fatal)
          mypy --install-types --non-interactive || true
          # Match your mypy package set
          mypy atticus api ingest retriever eval

      - name: Tests with coverage (>=90%)
        run: |
          pytest --maxfail=1 --disable-warnings \
                 --cov=atticus --cov=api --cov=retriever \
                 --cov-report=term-missing --cov-fail-under=90 -q
      - name: Smoke tests
        run: make smoke
      - name: Pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure
