name: Lint and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install project + dev tools
        run: |
          python -m pip install --upgrade pip
          # Installs your package and dev extras (ruff, mypy, pytest, pydantic, etc.)
          python -m pip install -e ".[dev]"
          python -m pip install pre-commit

      - name: Show tool versions
        run: |
          python --version
          ruff --version
          mypy --version
          pytest --version

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .

      - name: Type check
        run: |
          # Grab stubs for common third-party libs if available (non-fatal)
          mypy --install-types --non-interactive || true
          # Match your mypy package set
          mypy atticus api ingest retriever eval

      - name: Tests with coverage (>=90%)
        run: |
          pytest --maxfail=1 --disable-warnings \
                 --cov=atticus --cov=api --cov=retriever \
                 --cov-report=term-missing --cov-fail-under=90 -q
      - name: Pre-commit (all files)
        run: pre-commit run --all-files --show-diff-on-failure

  pgvector-check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector:0.5.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: atticus
        options: >-
          --health-cmd "pg_isready -U postgres -d atticus"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/atticus
      PGVECTOR_DIMENSION: 3072
      PGVECTOR_LISTS: 100
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install psql client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy

      - name: Verify pgvector schema
        run: make db.verify
