name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Next.js quality gates
        run: |
          pnpm run lint
          pnpm run typecheck
          pnpm run build

      - name: Runtime dependency audit (non-blocking)
        continue-on-error: true
        run: pnpm audit --prod

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Ruff lint
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .

      - name: Type check
        run: mypy

      - name: Pytest
        run: pytest

      - name: Generate API schema
        run: python scripts/generate_api_docs.py --output api/schema.json

      - name: Run evaluation
        run: python scripts/eval_run.py --json --output-dir eval/runs/release

      - name: Upload evaluation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-release
          path: eval/runs/release

      - name: Package release artifacts
        run: |
          mkdir -p release-artifacts
          mkdir -p eval/reports
          tar -czf release-artifacts/eval-reports.tar.gz eval/reports
          cp api/schema.json release-artifacts/api-schema.json
          tar -czf release-artifacts/docs-md.tar.gz docs/*.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            eval/runs/release/metrics.csv
            eval/runs/release/summary.json
            release-artifacts/api-schema.json
            release-artifacts/eval-reports.tar.gz
            release-artifacts/docs-md.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
